services:
  nginx-reverse-proxy:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    restart: unless-stopped
  flora-feed-next-js:
    build: .
    ports:
      - "3001:3000"
    restart: unless-stopped